name: CI
on:
  push:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Build (tests + coverage + detekt + spotless)
        run: ./gradlew --no-daemon build